
// Defines types and enums related to Projects, aligning with backend schemas.

export enum ProjectRoleEnum {
    VIEWER = "Viewer",
    EDITOR = "Editor",
    MODERATOR = "Moderator",
    ADMIN = "Admin",
    OWNER = "Owner",
}

export interface ProjectMember {
    uid: string;
    username: string | null;
    project_role: string;
    global_role?: string | null;
    avatar_url?: string;
    email?: string; // Added to match the backend response
}

export interface ProjectDetail {
    id: string;
    name: string;
    description: string | null;
    created_at: string; // ISO 8601 date string
    owner_uid: string;
    members: ProjectMember[];
}

export interface ProjectListDetail {
    id: string;
    name: string;
    description: string | null;
    user_project_role: string;
    user_global_role: string;
}

export interface PaginatedProjectListResponse {
    projects: ProjectListDetail[];
    pagination: {
        total: number;
    };
}

// --- Payloads for API Requests ---

export interface ProjectCreatePayload {
    id?: string; // Made optional as it's generated by the backend
    name: string;
    description: string | null;
}

export interface MemberInvitePayload {
    user_id?: string; 
    email?: string;
    role: ProjectRoleEnum;
}

// Kept for potential future use or legacy search components
export interface ProjectSearchResult {
    id: string;
    name: string;
    description: string | null;
    role: string; 
    members: ProjectMember[];
}

export interface PaginatedProjectSearchResponse {
    projects: ProjectSearchResult[];
    pagination: any;
}
